# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c404477f6a908a42f4cd793873e240cacd801712f3028a05217806cc3d7ee7fd97e7095847c7b6057310ac35bfb1e7e0e94c672deb17f1f4e593567a4f19e947

test:
  secret_key_base: 64ab1abe8532214b2b7ae2785ccbd6142be49cd08fb88387170fd630168658023efab4311e222988dc13f7023625c6d06d66627c74faca8b0bbd969181c7e6ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
